# Generated by Django 3.2.4 on 2021-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_no', models.IntegerField(max_length=10, unique=True)),
                ('item_desc', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
