# Generated by Django 3.2.4 on 2021-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
    ]
